[package]
name = "trans-gen"
version = "0.3.0-alpha.1"
authors = ["kuviman <kuviman@gmail.com>"]
description = "Generating trans code from Rust into other languages"
license = "MIT"
homepage = "https://github.com/kuviman/trans-gen"
edition = "2018"

[dev-dependencies]
tempfile = "3"

[dependencies]
trans-gen-core = { path = "core", version = "0.3.0-alpha" }
trans-gen-python = { path = "gens/python", version = "0.3.0-alpha" }
trans-gen-javascript = { path = "gens/javascript", version = "0.3.0-alpha" }
trans-gen-ruby = { path = "gens/ruby", version = "0.3.0-alpha" }
trans-gen-rust = { path = "gens/rust", version = "0.3.0-alpha" }
trans-gen-java = { path = "gens/java", version = "0.3.0-alpha" }
trans-gen-kotlin = { path = "gens/kotlin", version = "0.3.0-alpha" }
trans-gen-scala = { path = "gens/scala", version = "0.3.0-alpha" }
trans-gen-csharp = { path = "gens/csharp", version = "0.3.0-alpha" }
trans-gen-fsharp = { path = "gens/fsharp", version = "0.3.0-alpha" }
trans-gen-cpp = { path = "gens/cpp", version = "0.3.0-alpha" }
trans-gen-dlang = { path = "gens/dlang", version = "0.3.0-alpha" }
trans-gen-go = { path = "gens/go", version = "0.3.0-alpha" }