[package]
name = "trans-gen"
version = "0.4.0-alpha.5"
authors = ["kuviman <kuviman@gmail.com>"]
description = "Generating trans code from Rust into other languages"
license = "MIT"
homepage = "https://github.com/kuviman/trans-gen"
edition = "2018"

[dev-dependencies]
tempfile = "3"

[dependencies]
trans = { path = "trans", version = "0.4.0-alpha" }
serde = { version = "1", features = ["derive"] }