name: trans-gen-test
version: 0.5.0

dependencies:
  - base
  - containers
  - text
  - binary
  - bytestring
  - network

executables:
  trans-gen-test:
    main: Main.hs
    source-dirs: src
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    default-extensions:
      - ScopedTypeVariables
      - TypeSynonymInstances
      - FlexibleInstances
      - NamedFieldPuns
      - DuplicateRecordFields