on: [push, pull_request]

name: Continuous integration

jobs:
  build-test:
    name: Build and run package tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - uses: actions-rs/cargo@v1
        with:
          command: test --release

      - name: Build testing
      - uses: actions-rs/cargo@v1
        with:
          command: build --release --example testing

      - name: Update testing branch
        run: |
          git config --global user.name 'CI'
          git config --global user.email '<>'
          git fetch origin testing
          git worktree add testing-branch testing
          cargo run --release --example testing -- generate testing-branch/generated-code
          pushd testing-branch
          git add .
          git diff --cached --exit-code || git commit -m "Update generated code"
          popd
          rm -rf branch
          git worktree prune
          git push origin testing
