on: [push, pull_request]

name: Continuous integration

jobs:
  build-test:
    name: Build and run package tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Run cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --release

      - name: Build testing binary
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --example testing

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: testing
          path: target/release/examples/testing

  test-languages:
    name: Test ${{ matrix.language }}
    needs: build-test
    strategy:
      matrix:
        include:
          - language: C++
            lang: cpp
            uses: docker://gcc
          - language: C#
            lang: csharp
            uses: docker://mcr.microsoft.com/dotnet/sdk
          - language: D
            lang: dlang
            uses: docker://dlanguage/dmd
          - language: F#
            lang: fsharp
            uses: docker://mcr.microsoft.com/dotnet/sdk
          - language: Go
            lang: go
            uses: docker://golang
          - language: Java
            lang: java
            uses: docker://maven
          - language: JavaScript
            lang: javascript
            uses: docker://node
          - language: Kotlin
            lang: kotlin
            uses: docker://maven
          # - language: Markdown
          #   lang: markdown
          #   uses: docker://???
          - language: Python
            lang: python
            uses: docker://python
          - language: Ruby
            lang: ruby
            uses: docker://ruby
          - language: Rust
            lang: rust
            uses: docker://rust
          - language: Scala
            lang: scala
            uses: docker://maven
          - language: TypeScript
            lang: typescript
            uses: docker://node
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: testing

      - name: Prepare testing binary
        run: chmod +x testing

      - name: Run tests
        uses: ${{ matrix.uses }}
        with:
          args: ./testing --lang=${{ matrix.lang }} test

  update-testing-branch:
    name: Update testing branch
    needs:
      - build-test
      - test-languages
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: testing

      - name: Update testing branch
        run: |
          git config --global user.name 'CI'
          git config --global user.email '<>'
          git fetch origin testing
          git worktree add testing-branch testing
          chmod +x testing
          ./testing generate testing-branch/generated-code
          pushd testing-branch
          git add .
          git diff --cached --exit-code || git commit -m "Update generated code"
          popd
          rm -rf branch
          git worktree prune
          git push origin testing
