on: [push, pull_request]

name: Continuous integration

jobs:
  ci:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - uses: actions-rs/cargo@v1
        with:
          command: test

      - name: aicup2020-codecraft
        run: |
          git config --global user.name 'CI'
          git config --global user.email '<>'
          git fetch origin aicup2020-codecraft
          bash examples/aicup2020-codecraft/update-branch.sh
          git push origin aicup2020-codecraft
